name: pub-sub-application
extensions:
- name: dapr
  components-path: "./dapr/components/"
  services:
    dapr-subscribe:
      http-port: 7002
      grpc-port: 7003
    dapr-publisher:
      http-port: 8002
      grpc-port: 8003
      enabled: true

services:
- name: dapr-subscribe
  project: DaprSubscribe\DaprSubscribe.csproj
  bindings:
  - port: 7001
- name: dapr-publisher
  project: DaprPublisher\DaprPublisher.csproj
- name: redis
  image: redis
  bindings:
    - port: 6973
      containerPort: 6379
